### ISSUE TITLE
symlinked files could be deleted

### ISSUE THREAD

**Issue by mixmix** [arj03/dat-shared-files#3]
when I looked at what the symlinks were I found that they just pointed to the raw file... 

This was surprising to me, because I just downloaded a video I wanted to share, so it's in `~/Downloads`, then I shared it on Patchbay (it worked like a treat!) but then at some point in the future I'm gonna drop the beefy files in my `~/Downloads` folder because I treat it like a temp folder.

My understanding is that this will gut the dat sharing ? I think a copy of the raw file should be moved into place in that folder....

**Comment by arj03** [comment]
It will, but on the other hand if you shared the link directly from that folder and deleted it, it would be the same result. I do understand the concern, it's about the mental model of how this works, I'll see if that can be more clear in the README. I was also thinking of added a "clean stale links" functionality.

**Comment by mixmix** [comment]
I propose you copy the file to the .dat-file-share folder, then people can
delete things from eg their downloads folder and not worry
